---
include:
  - board: nice_nano_v2
    shield: kyria_rev2_left
  - board: nice_nano_v2
    shield: kyria_rev2_right
  - board: nice_nano_v2
    shield: splitkb_aurora_sweep_left
  - board: nice_nano_v2
    shield: splitkb_aurora_sweep_right

board_root: .
