---
include:
  - board: nice_nano//zmk
    shield: kyria_rev2_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano//zmk
    shield: kyria_rev2_right
  - board: nice_nano//zmk
    shield: splitkb_aurora_sweep_left
  - board: nice_nano//zmk
    shield: splitkb_aurora_sweep_right
  - board: nice_nano//zmk
    shield: berylline_left
  - board: nice_nano//zmk
    shield: berylline_right
